source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
inhibit_all_warnings!

target 'TEST' do
  use_frameworks!

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end

  pod 'SocketRocket', '~> 0.5.1'
  
  # 通过pod去制定对应的subspec.可以在/node_modules/react-native/React.podspec文件内查看已提供的subspec
#  pod 'React', :path => '../node_modules/react-native/'
#  pod 'React-Core', :path => '../node_modules/react-native/'
#  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
#
#  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#  pod 'React-perflogger', :path => '../node_modules/react-native/ReactCommon/reactperflogger'
#  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#  pod 'FBReactNativeSpec', :path => '../node_modules/react-native/React/FBReactNativeSpec'
#  pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector'
#  pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
#  pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native/ReactCommon'
#  pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired'
#  pod 'React-logger', :path => '../node_modules/react-native/ReactCommon/logger'
#  pod 'React-callinvoker', :path => '../node_modules/react-native/ReactCommon/callinvoker'
#  pod 'React-runtimeexecutor', :path => '../node_modules/react-native/ReactCommon/runtimeexecutor'
#
#  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec'
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

end
